bank_operation_tiers_index:
    path:     /
    defaults: { _controller: "BankBundle:OperationTiers:index" }
    methods:  GET
bank_operation_tiers_new:
    path:     /new
    defaults: { _controller: "BankBundle:OperationTiers:new" }
    methods:  [GET, POST]

bank_operation_tiers_edit:
    path:     /edit/{id}
    defaults: { _controller: "BankBundle:OperationTiers:edit" }
    methods:  [GET, POST]
